spring:
  profiles:
    active: prod
  datasource:
    driverClassName: org.postgresql.Driver
    # driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/minimaltodo
    username: postgres
    password: ElTesoro@0258
    validationQuery: SELECT 1
    hikari:
      maximumPoolSize: 3
      minimumIdle: 1
      connectionTestQuery: select 1
      idleTimeout: 600000
      maxLifetime: 1800000
      poolName: PotatoPool
      connectionTimeout: 30000
  devtools:
    add-properties: false
  thymeleaf:
    check-template-location: false
  jpa:
    open-in-view: false
    # show-sql: false
    # show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # dialect: org.hibernate.dialect.MySQLDialect
        initialize: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

# logging:
  # level:
    # web: DEBUG
    # com.zaxxer.hikari: DEBUG

jwt:
  secret: potatoSalad

